### ISSUE TITLE
[Overlay] Dragging Calibration of body proportion.

### ISSUE THREAD

**Issue by astomx** [SlimeVR/SlimeVR-Rust#202]
I have an idea that may help to better calibrate the proportions of the body to get the Slime in 1X1 calibration

The idea is to create an app within steam that will work exclusively for calibrating the position of the trackers.

This application is made for use with SteamVR, and when you enter it asks which trackers you will use with SlimeVR.
After selecting the desired types of trackers, squares representing the trackers will appear in front of the user.
The next step now is to grab the tracker within the application and drag it to where the corresponding tracker is in the body.
After doing this with all the trackers, the program will create a code containing the skeleton configuration that can be used in the SlimeVR software.

**Comment by TheButlah** [comment]
Yes, this is something that would make sense to be in the slimevr overlay. But I have not implemented it, as I don't have bandwidth for it rn.

If you wish to work on it, by all means!
